security:
    encoders:
        App\Entity\User:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: token
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # main:
        #     anonymous: true

        login:
            pattern: ^/api/user/login
            stateless: true
            anonymous: true

        register:
            pattern: ^/api/user/add
            stateless: true
            anonymous: true

        location:
            pattern: ^/api/location
            stateless: true
            anonymous: true

        ads:
            pattern: ^/api/ad/ads
            stateless: true
            anonymous: true

        recent_ads:
            pattern: ^/api/ad/recent_ads
            stateless: true
            anonymous: true

        api:
            pattern: ^/api
            # anonymous: true
            # lazy: true
            stateless: true
            logout: ~
                # path: user_logout
            # provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\Authenticator

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
